#!/usr/bin/env bash
# test: go test + go vet on frr-agent and bgp-dashboard.
# usage: bash tests/fabric-dashboard-unit.sh
set -euo pipefail
R=$(cd "$(dirname "$0")/.." && pwd)
cd "$R/frr-agent"
go test ./...
go vet ./...
cd "$R/dashboard"
go test ./...
go vet ./...
echo "TEST PASS: frr-agent and bgp-dashboard go test + go vet"
